version: '3'

networks:
  ntopng:
    driver: "bridge"

services:

  ntopng:
    container_name: ntopng
    image: rickymbru/ntopng
    build:
      context: ./docker/ntopng
      dockerfile: Dockerfile    
    command: ["/etc/ntopng/ntopng.conf"]
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    ports:
      - "3000:3000"    
    restart: unless-stopped
    networks:
      - ntopng
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    command: --save 900 1
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    networks:
      - ntopng    
  
  nprobe-pirai:
    container_name: nprobe-pirai
    image: rickymbru/nprobe
    build:
      context: ./docker/nprobe
      dockerfile: Dockerfile       
    command: --collector-port 2055 --zmq tcp://*:5557 -i none -n none
    ports:
      - "2055:2055/udp"
    networks:
      - ntopng

  nprobe-barra-pirai:
    container_name: nprobe-barra-pirai
    image: rickymbru/nprobe
    build:
      context: ./docker/nprobe
      dockerfile: Dockerfile       
    command: --collector-port 2230 --zmq tcp://*:5230 -i none -n none
    ports:
      - "2230:2230/udp"
    networks:
      - ntopng   

